Create 0303-range-sum-query-immutable.js
neetcode-gh/leetcode pull request #2541
Opened 2023-06-06 15:44 UTC by aadil42

Solved range-sum-query-immutable.

File(s) Added: 0303-range-sum-query-immutable.js
Language(s) Used: JavaScript
Submission URL: https://leetcode.com/problems/range-sum-query-immutable/submissions/946368367/

[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _0001-two-sum.py, 0002-add-two-numbers.py, etc..._
- **Language(s) Used**: _python, javascript, etc..._
- **Submission URL**: _https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

2023-06-30 13:10 UTC, aakhtar3 requested changes

2023-06-30 13:10 UTC, aakhtar3 commented on javascript/0303-range-sum-query-immutable.js
> +var NumArray = function(nums) {
Suggestion: Use Class

2023-07-01 13:42 UTC, aadil42 commented on javascript/0303-range-sum-query-immutable.js
> +var NumArray = function(nums) {
It's done.

2023-07-01 13:51 UTC, aakhtar3 approved these changes

2023-07-01 13:51 UTC, merged