Create 0304-range-sum-query-2d-immutable.js
neetcode-gh/leetcode pull request #2559
Opened 2023-06-09 05:40 UTC by aadil42

Added solution for range-sum-query-2d-immutable in JS

File(s) Added: 0304-range-sum-query-2d-immutable.js
Language(s) Used: JavaScript
Submission URL: https://leetcode.com/problems/range-sum-query-2d-immutable/submissions/861807012/

2023-06-30 13:04 UTC, aakhtar3 requested changes

2023-06-30 13:04 UTC, aakhtar3 commented on javascript/0304-range-sum-query-2d-immutable.js
> + var NumMatrix = function(matrix) {
Suggestion: Create class

2023-07-01 14:14 UTC, aadil42 commented on javascript/0304-range-sum-query-2d-immutable.js
> + var NumMatrix = function(matrix) {
done.

2023-07-01 20:36 UTC, aakhtar3 approved these changes

2023-07-01 20:36 UTC, merged