Create 0901-online-stock-span.js
neetcode-gh/leetcode pull request #2613
Opened 2023-06-21 14:43 UTC by aadil42

Added solution for online-stock-span in JS.

File(s) Added: 0901-online-stock-span.js
Language(s) Used: JavaScript
Submission URL: https://leetcode.com/problems/online-stock-span/submissions/976405985/

2023-06-30 12:50 UTC, aakhtar3 requested changes

2023-06-30 12:50 UTC, aakhtar3 commented on javascript/0901-online-stock-span.js
> +      return this.stack[this.stack.length - 1];
Suggestion: add validation check

```js
return this.isEmpty()
	? null
	: ...
```

2023-07-02 15:40 UTC, aadil42 commented on javascript/0901-online-stock-span.js
> +      return this.stack[this.stack.length - 1];
Done.

2023-07-02 15:53 UTC, aakhtar3 approved these changes

2023-07-02 15:54 UTC, merged