1822 - Sign of the Product of an Array
neetcode-gh/leetcode pull request #2688
Opened 2023-07-10 20:25 UTC by AHTHneeuhl

[//]: # "Pull Request Template"
[//]: # "Replace the placeholder values in the template below"

- **File(s) Modified**: _1822-sign-of-the-product-of-an-array_
- **Language(s) Used**: _python, javascript, typescript etc..._
- **Submission URL**: _https://leetcode.com/submissions/detail/991294716/_

[//]: # "Getting the Submission URL"
[//]: # "Go to the leetcode [`Submissions tab`](https://user-images.githubusercontent.com/71089234/180188604-b1ecaf90-bf27-4fd6-a559-5567aebf8930.png)"
[//]: # "and [click on the `Accepted` status of your submission.](https://user-images.githubusercontent.com/71089234/180189321-1a48c33f-aa65-4b29-8aaa-685f4f5f8c9e.png)]"
[//]: # "Finally copy the URL from the nav bar, it should look like https://leetcode.com/problems/[problem-name]/submissions/xxxxxxxxx/"

### Important
Please make sure the file name is lowercase and a duplicate file does not already exist before merging.

2023-07-10 20:30 UTC, aakhtar3 requested changes

2023-07-10 20:30 UTC, aakhtar3 commented on javascript/1822-sign-of-the-product-of-an-array.js
> +        else if (num < 0) sign = -1 * sign;
Suggestion: Avoid else

```js
if (canSkip) continue;
if (canBreak) break;
if (canExit) return;

// else ...

if (isPositive) sign *= -1;
```

2023-07-10 20:38 UTC, AHTHneeuhl commented on javascript/1822-sign-of-the-product-of-an-array.js
> +        else if (num < 0) sign = -1 * sign;
Updated the code!

2023-07-11 19:37 UTC, aakhtar3 approved these changes

2023-07-11 19:37 UTC, merged